QUERY_BLOCK_LATEST = 0
QUERY_BLOCK_FROM_HEIGHT = 1
RESPONSE_BLOCKCHAIN = 2

LOAD_SUCCESS = 1
HEIGHT_TOO_LOW = 2
LOAD_FAILS = 3
NOTNEXTBLOCK = 4

SERVICE = 1000

DESCOVERY = 1
TRANSACTION = 2
SYNCHRONIZATION = 3
CONSENSUS = 4

EXCHANGENODE = 1
BLOCKREQUEST = 1
BLOCKBROADCAST = 2
MESSAGEREQUEST = 3

FROM = 1
TO = 2

SUCCESS_VERTIFY = 1
ERROR_BLOCK_HASH_VERTIFY = 2
WARNING_PREVIOUS_HASH_NOT_EQUAL = 3
NOT_FOUND_BLOCK = 4