# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import grpc_pb2 as grpc__pb2


class DiscoveryStub(object):

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ExchangeNode = channel.unary_unary(
        '/Discovery/ExchangeNode',
        request_serializer=grpc__pb2.Node.SerializeToString,
        response_deserializer=grpc__pb2.Node.FromString,
        )
    self.Hello = channel.unary_unary(
        '/Discovery/Hello',
        request_serializer=grpc__pb2.Message.SerializeToString,
        response_deserializer=grpc__pb2.Message.FromString,
        )


class DiscoveryServicer(object):

  def ExchangeNode(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Hello(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DiscoveryServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ExchangeNode': grpc.unary_unary_rpc_method_handler(
          servicer.ExchangeNode,
          request_deserializer=grpc__pb2.Node.FromString,
          response_serializer=grpc__pb2.Node.SerializeToString,
      ),
      'Hello': grpc.unary_unary_rpc_method_handler(
          servicer.Hello,
          request_deserializer=grpc__pb2.Message.FromString,
          response_serializer=grpc__pb2.Message.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Discovery', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class TransactionStub(object):

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.BlockBroadcast = channel.unary_unary(
        '/Transaction/BlockBroadcast',
        request_serializer=grpc__pb2.Block.SerializeToString,
        response_deserializer=grpc__pb2.Message.FromString,
        )


class TransactionServicer(object):

  def BlockBroadcast(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TransactionServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'BlockBroadcast': grpc.unary_unary_rpc_method_handler(
          servicer.BlockBroadcast,
          request_deserializer=grpc__pb2.Block.FromString,
          response_serializer=grpc__pb2.Message.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Transaction', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class SynchronizationStub(object):

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.From = channel.unary_unary(
        '/Synchronization/From',
        request_serializer=grpc__pb2.Message.SerializeToString,
        response_deserializer=grpc__pb2.Block.FromString,
        )
    self.To = channel.unary_unary(
        '/Synchronization/To',
        request_serializer=grpc__pb2.Block.SerializeToString,
        response_deserializer=grpc__pb2.Message.FromString,
        )


class SynchronizationServicer(object):

  def From(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def To(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SynchronizationServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'From': grpc.unary_unary_rpc_method_handler(
          servicer.From,
          request_deserializer=grpc__pb2.Message.FromString,
          response_serializer=grpc__pb2.Block.SerializeToString,
      ),
      'To': grpc.unary_unary_rpc_method_handler(
          servicer.To,
          request_deserializer=grpc__pb2.Block.FromString,
          response_serializer=grpc__pb2.Message.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Synchronization', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
